[2025-05-02T01:43:34.281+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spacex_orbitflow_etl_dbt.run_java_etl manual__2025-05-02T01:43:31.445412+00:00 [queued]>
[2025-05-02T01:43:34.287+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spacex_orbitflow_etl_dbt.run_java_etl manual__2025-05-02T01:43:31.445412+00:00 [queued]>
[2025-05-02T01:43:34.287+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-05-02T01:43:34.294+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): run_java_etl> on 2025-05-02 01:43:31.445412+00:00
[2025-05-02T01:43:34.307+0000] {standard_task_runner.py:60} INFO - Started process 126 to run task
[2025-05-02T01:43:34.313+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spacex_orbitflow_etl_dbt', 'run_java_etl', 'manual__2025-05-02T01:43:31.445412+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_orchestrate.py', '--cfg-path', '/tmp/tmprhptpxsr']
[2025-05-02T01:43:34.317+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask run_java_etl
[2025-05-02T01:43:34.359+0000] {task_command.py:423} INFO - Running <TaskInstance: spacex_orbitflow_etl_dbt.run_java_etl manual__2025-05-02T01:43:31.445412+00:00 [running]> on host e3b087e51739
[2025-05-02T01:43:34.437+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='orbitflow' AIRFLOW_CTX_DAG_ID='spacex_orbitflow_etl_dbt' AIRFLOW_CTX_TASK_ID='run_java_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T01:43:31.445412+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T01:43:31.445412+00:00'
[2025-05-02T01:43:34.440+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-02T01:43:34.442+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/etl-java && ./run.sh ']
[2025-05-02T01:43:34.451+0000] {subprocess.py:86} INFO - Output:
[2025-05-02T01:43:34.455+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /opt/etl-java: No such file or directory
[2025-05-02T01:43:34.455+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-02T01:43:34.471+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-02T01:43:34.475+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spacex_orbitflow_etl_dbt, task_id=run_java_etl, execution_date=20250502T014331, start_date=20250502T014334, end_date=20250502T014334
[2025-05-02T01:43:34.481+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task run_java_etl (Bash command failed. The command returned a non-zero exit code 1.; 126)
[2025-05-02T01:43:34.502+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-02T01:43:34.518+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
